services:
  app:
    image: "863518453426.dkr.ecr.ap-northeast-2.amazonaws.com/game_mate:latest"
    platform: linux/amd64
    container_name: app
    ports:
      - "8080:8080"
    environment:
      MYSQL_USERNAME: "${MYSQL_USERNAME}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_URL: "${MYSQL_URL}"
      JPA_HIBERNATE_DDL: "${JPA_HIBERNATE_DDL}"
      JWT_SECRET: "${JWT_SECRET}"
      AWS_ACCESS_KEY: "${AWS_ACCESS_KEY}"
      AWS_SECRET_KEY: "${AWS_SECRET_KEY}"
      AWS_BUCKET: "${AWS_BUCKET}"
      AWS_REGION: "${AWS_REGION}"
      AWS_STACK_AUTO: "${AWS_STACK_AUTO}"
      OAUTH2_GOOGLE_CLIENT_ID: "${OAUTH2_GOOGLE_CLIENT_ID}"
      OAUTH2_GOOGLE_CLIENT_SECRET: "${OAUTH2_GOOGLE_CLIENT_SECRET}"
      OAUTH2_KAKAO_CLIENT_ID : "${OAUTH2_KAKAO_CLIENT_ID}"
      OAUTH2_KAKAO_CLIENT_SECRET: "${OAUTH2_KAKAO_CLIENT_SECRET}"
      EMAIL_USERNAME: "${EMAIL_USERNAME}"
      EMAIL_APP_PASSWORD: "${EMAIL_APP_PASSWORD}"
      GEMINI_URL: "${GEMINI_URL}"
      GEMINI_KEY: "${GEMINI_KEY}"
      REDIS_HOST: "${REDIS_HOST}"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"


volumes:
  db-data:
